import { ModelOption } from "./types";

/**
 * Build a robust Unsloth Google Colab notebook.
 * Dataset is base64-encoded so special characters never break the notebook.
 * Uses patterns from official Unsloth Colab notebooks (2026).
 */
export function buildUnslothNotebook(opts: {
  model: ModelOption;
  datasetJsonl: string;
  epochs: number;
  learningRate: number;
  maxSeqLength?: number;
}): string {
  const {
    model,
    datasetJsonl,
    epochs,
    learningRate,
    maxSeqLength = 2048,
  } = opts;

  const b64 = Buffer.from(datasetJsonl, "utf8").toString("base64");

  const nEpochs = Math.min(Math.max(epochs, 1), 3);
  const lr = learningRate || 2e-4;
  const modelName = model.unslothId;

  const cells: any[] = [
    {
      cell_type: "markdown",
      metadata: {},
      source: [
        `# EasyFineTune — Free training (Unsloth + Colab T4)\n`,
        `\n`,
        `**Model:** ${model.name}  \n`,
        `**HF id:** \`${modelName}\`\n`,
        `\n`,
        `### Before you start\n`,
        `1. **Runtime → Change runtime type → T4 GPU** (must be GPU, not CPU)\n`,
        `2. **Runtime → Run all**\n`,
        `3. Wait for training to finish (often 10–40 min)\n`,
        `4. Download the \`lora_model\` folder from the left Files panel\n`,
        `\n`,
        `If a cell fails: **Runtime → Restart session**, then Run all again.\n`,
        `Do **not** run cells out of order.\n`,
      ],
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# Cell 1 — Install (ignore the long pip log)\n`,
        `%%capture\n`,
        `import os, sys\n`,
        `!pip install -q --upgrade pip\n`,
        `!pip install -q unsloth\n`,
        `!pip install -q --upgrade --no-cache-dir transformers datasets accelerate bitsandbytes trl peft\n`,
        `print("Install done. Restart runtime ONLY if the next cell fails to import unsloth.")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# Cell 2 — Check GPU\n`,
        `import torch\n`,
        `print("CUDA available:", torch.cuda.is_available())\n`,
        `if torch.cuda.is_available():\n`,
        `    print("GPU:", torch.cuda.get_device_name(0))\n`,
        `    print("VRAM (GB):", round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2))\n`,
        `else:\n`,
        `    raise SystemExit(\n`,
        `        "No GPU! Go to Runtime → Change runtime type → Hardware accelerator → T4 GPU, then Runtime → Run all."\n`,
        `    )\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# Cell 3 — Load model (4-bit so it fits free T4)\n`,
        `from unsloth import FastLanguageModel\n`,
        `import torch\n`,
        `\n`,
        `max_seq_length = ${maxSeqLength}\n`,
        `model_name = "${modelName}"\n`,
        `\n`,
        `model, tokenizer = FastLanguageModel.from_pretrained(\n`,
        `    model_name = model_name,\n`,
        `    max_seq_length = max_seq_length,\n`,
        `    dtype = None,\n`,
        `    load_in_4bit = True,\n`,
        `)\n`,
        `\n`,
        `model = FastLanguageModel.get_peft_model(\n`,
        `    model,\n`,
        `    r = 16,\n`,
        `    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",\n`,
        `                      "gate_proj", "up_proj", "down_proj"],\n`,
        `    lora_alpha = 16,\n`,
        `    lora_dropout = 0,\n`,
        `    bias = "none",\n`,
        `    use_gradient_checkpointing = "unsloth",\n`,
        `    random_state = 3407,\n`,
        `)\n`,
        `print("Model + LoRA ready")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# Cell 4 — Load your dataset (embedded as base64)\n`,
        `import base64, tempfile, json\n`,
        `from datasets import Dataset\n`,
        `\n`,
        `B64 = """${b64}"""\n`,
        `raw = base64.b64decode(B64).decode("utf-8")\n`,
        `lines = [ln.strip() for ln in raw.splitlines() if ln.strip()]\n`,
        `rows = []\n`,
        `for i, ln in enumerate(lines):\n`,
        `    try:\n`,
        `        obj = json.loads(ln)\n`,
        `    except Exception as e:\n`,
        `        print(f"Skip line {i+1}: {e}")\n`,
        `        continue\n`,
        `    if "messages" in obj and isinstance(obj["messages"], list):\n`,
        `        rows.append({"messages": obj["messages"]})\n`,
        `    elif "prompt" in obj and "completion" in obj:\n`,
        `        rows.append({\n`,
        `            "messages": [\n`,
        `                {"role": "user", "content": str(obj["prompt"])},\n`,
        `                {"role": "assistant", "content": str(obj["completion"])},\n`,
        `            ]\n`,
        `        })\n`,
        `    else:\n`,
        `        print(f"Skip line {i+1}: need messages[] or prompt+completion")\n`,
        `\n`,
        `if len(rows) == 0:\n`,
        `    raise SystemExit("No valid examples in dataset.")\n`,
        `\n`,
        `dataset = Dataset.from_list(rows)\n`,
        `print(f"Loaded {len(dataset)} examples")\n`,
        `print("Sample:", dataset[0])\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# Cell 5 — Format conversations to text\n`,
        `def to_text(example):\n`,
        `    msgs = example["messages"]\n`,
        `    try:\n`,
        `        text = tokenizer.apply_chat_template(\n`,
        `            msgs, tokenize=False, add_generation_prompt=False\n`,
        `        )\n`,
        `    except Exception:\n`,
        `        parts = []\n`,
        `        for m in msgs:\n`,
        `            role = m.get("role", "user")\n`,
        `            content = m.get("content", "")\n`,
        `            parts.append(f"{role}: {content}")\n`,
        `        text = "\\n".join(parts)\n`,
        `    return {"text": text}\n`,
        `\n`,
        `dataset = dataset.map(to_text, remove_columns=dataset.column_names)\n`,
        `print("Formatted sample:")\n`,
        `print(dataset[0]["text"][:500])\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# Cell 6 — Train\n`,
        `from trl import SFTTrainer\n`,
        `from transformers import TrainingArguments\n`,
        `from unsloth import is_bfloat16_supported\n`,
        `\n`,
        `n_examples = len(dataset)\n`,
        `max_steps = min(max(60, n_examples), 200)\n`,
        `\n`,
        `args = TrainingArguments(\n`,
        `    per_device_train_batch_size = 2,\n`,
        `    gradient_accumulation_steps = 4,\n`,
        `    warmup_steps = 5,\n`,
        `    num_train_epochs = ${nEpochs},\n`,
        `    max_steps = max_steps if n_examples < 50 else -1,\n`,
        `    learning_rate = ${lr},\n`,
        `    fp16 = not is_bfloat16_supported(),\n`,
        `    bf16 = is_bfloat16_supported(),\n`,
        `    logging_steps = 1,\n`,
        `    optim = "adamw_8bit",\n`,
        `    weight_decay = 0.01,\n`,
        `    lr_scheduler_type = "linear",\n`,
        `    seed = 3407,\n`,
        `    output_dir = "outputs",\n`,
        `    report_to = "none",\n`,
        `    save_strategy = "no",\n`,
        `)\n`,
        `\n`,
        `trainer = SFTTrainer(\n`,
        `    model = model,\n`,
        `    tokenizer = tokenizer,\n`,
        `    train_dataset = dataset,\n`,
        `    dataset_text_field = "text",\n`,
        `    max_seq_length = max_seq_length,\n`,
        `    packing = False,\n`,
        `    args = args,\n`,
        `)\n`,
        `\n`,
        `print("Starting training…")\n`,
        `stats = trainer.train()\n`,
        `print(stats)\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# Cell 7 — Save LoRA adapter\n`,
        `model.save_pretrained("lora_model")\n`,
        `tokenizer.save_pretrained("lora_model")\n`,
        `print("Saved to ./lora_model")\n`,
        `print("In the left Files panel: right-click lora_model → Download")\n`,
        `print("Or zip it:")\n`,
        `!zip -r lora_model.zip lora_model\n`,
        `print("Download lora_model.zip from the Files panel.")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "markdown",
      metadata: {},
      source: [
        `## Done\n`,
        `\n`,
        `- Download \`lora_model\` (or \`lora_model.zip\`) from the left sidebar.\n`,
        `- Use it with the same base model via PEFT / Unsloth / vLLM.\n`,
        `\n`,
        `If Colab disconnected mid-run: free tier sessions can drop after idle time.  \n`,
        `Re-open the notebook, set **T4 GPU**, and **Run all** again.\n`,
      ],
    },
  ];

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3",
      },
      language_info: {
        name: "python",
        version: "3.10.0",
      },
      accelerator: "GPU",
      colab: {
        provenance: [],
        gpuType: "T4",
      },
    },
    cells,
  };

  return JSON.stringify(notebook, null, 2);
}
