import { ModelOption } from "./types";

/**
 * Beginner-friendly Unsloth Colab notebook.
 * - Base64 dataset (safe)
 * - Step-by-step cells
 * - Test chat after training
 * - Clear how to use your model instructions
 */
export function buildUnslothNotebook(opts: {
  model: ModelOption;
  datasetJsonl: string;
  epochs: number;
  learningRate: number;
  maxSeqLength?: number;
}): string {
  const {
    model,
    datasetJsonl,
    epochs,
    learningRate,
    maxSeqLength = 2048,
  } = opts;

  const b64 = Buffer.from(datasetJsonl, "utf8").toString("base64");
  const nEpochs = Math.min(Math.max(epochs, 1), 3);
  const lr = learningRate || 2e-4;
  const modelName = model.unslothId;

  const cells: any[] = [
    {
      cell_type: "markdown",
      metadata: {},
      source: [
        `# EasyFineTune — Train your model (for beginners)\n`,
        `\n`,
        `**Model:** ${model.name}  \n`,
        `**ID:** \`${modelName}\`\n`,
        `\n`,
        `---\n`,
        `\n`,
        `## What you will do (3 steps)\n`,
        `\n`,
        `| Step | Action |\n`,
        `|------|--------|\n`,
        `| 1 | Set GPU: **Runtime → Change runtime type → T4 GPU** |\n`,
        `| 2 | Click **Runtime → Run all** and wait |\n`,
        `| 3 | Download your trained model (last cells) |\n`,
        `\n`,
        `Keep this tab open. Free Colab can disconnect if you leave it idle.\n`,
        `\n`,
        `If something fails: **Runtime → Restart session** → Run all again.\n`,
      ],
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# ========== STEP 1: Install tools ==========\n`,
        `# This can take 1–3 minutes. Wait until it finishes.\n`,
        `%%capture\n`,
        `!pip install -q --upgrade pip\n`,
        `!pip install -q unsloth\n`,
        `!pip install -q transformers datasets accelerate bitsandbytes trl peft\n`,
        `print("OK — install finished")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# ========== STEP 2: Check GPU ==========\n`,
        `import torch\n`,
        `print("GPU found:", torch.cuda.is_available())\n`,
        `if not torch.cuda.is_available():\n`,
        `    raise SystemExit(\n`,
        `        "NO GPU. Do this: Runtime → Change runtime type → Hardware accelerator → T4 GPU → Save. Then Runtime → Run all."\n`,
        `    )\n`,
        `print("GPU name:", torch.cuda.get_device_name(0))\n`,
        `print("OK — GPU is ready")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# ========== STEP 3: Load the base model ==========\n`,
        `from unsloth import FastLanguageModel\n`,
        `\n`,
        `max_seq_length = ${maxSeqLength}\n`,
        `model_name = "${modelName}"\n`,
        `\n`,
        `model, tokenizer = FastLanguageModel.from_pretrained(\n`,
        `    model_name = model_name,\n`,
        `    max_seq_length = max_seq_length,\n`,
        `    dtype = None,\n`,
        `    load_in_4bit = True,\n`,
        `)\n`,
        `\n`,
        `model = FastLanguageModel.get_peft_model(\n`,
        `    model,\n`,
        `    r = 16,\n`,
        `    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",\n`,
        `                      "gate_proj", "up_proj", "down_proj"],\n`,
        `    lora_alpha = 16,\n`,
        `    lora_dropout = 0,\n`,
        `    bias = "none",\n`,
        `    use_gradient_checkpointing = "unsloth",\n`,
        `    random_state = 3407,\n`,
        `)\n`,
        `print("OK — model loaded")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# ========== STEP 4: Load your training data ==========\n`,
        `import base64, json\n`,
        `from datasets import Dataset\n`,
        `\n`,
        `B64 = """${b64}"""\n`,
        `raw = base64.b64decode(B64).decode("utf-8")\n`,
        `lines = [ln.strip() for ln in raw.splitlines() if ln.strip()]\n`,
        `rows = []\n`,
        `for i, ln in enumerate(lines):\n`,
        `    try:\n`,
        `        obj = json.loads(ln)\n`,
        `    except Exception:\n`,
        `        continue\n`,
        `    if "messages" in obj and isinstance(obj["messages"], list):\n`,
        `        rows.append({"messages": obj["messages"]})\n`,
        `    elif "prompt" in obj and "completion" in obj:\n`,
        `        rows.append({\n`,
        `            "messages": [\n`,
        `                {"role": "user", "content": str(obj["prompt"])},\n`,
        `                {"role": "assistant", "content": str(obj["completion"])},\n`,
        `            ]\n`,
        `        })\n`,
        `\n`,
        `if len(rows) == 0:\n`,
        `    raise SystemExit("No valid examples found in your dataset.")\n`,
        `\n`,
        `dataset = Dataset.from_list(rows)\n`,
        `print(f"OK — loaded {len(dataset)} examples")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# ========== STEP 5: Format data for training ==========\n`,
        `def to_text(example):\n`,
        `    msgs = example["messages"]\n`,
        `    try:\n`,
        `        text = tokenizer.apply_chat_template(\n`,
        `            msgs, tokenize=False, add_generation_prompt=False\n`,
        `        )\n`,
        `    except Exception:\n`,
        `        parts = []\n`,
        `        for m in msgs:\n`,
        `            parts.append(str(m.get("role", "user")) + ": " + str(m.get("content", "")))\n`,
        `        text = "\\n".join(parts)\n`,
        `    return {"text": text}\n`,
        `\n`,
        `dataset = dataset.map(to_text, remove_columns=dataset.column_names)\n`,
        `print("OK — data formatted")\n`,
        `print("--- sample ---")\n`,
        `print(dataset[0]["text"][:400])\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# ========== STEP 6: Train (this is the long step) ==========\n`,
        `from trl import SFTTrainer\n`,
        `from transformers import TrainingArguments\n`,
        `from unsloth import is_bfloat16_supported\n`,
        `\n`,
        `n_examples = len(dataset)\n`,
        `max_steps = min(max(60, n_examples), 200)\n`,
        `\n`,
        `args = TrainingArguments(\n`,
        `    per_device_train_batch_size = 2,\n`,
        `    gradient_accumulation_steps = 4,\n`,
        `    warmup_steps = 5,\n`,
        `    num_train_epochs = ${nEpochs},\n`,
        `    max_steps = max_steps if n_examples < 50 else -1,\n`,
        `    learning_rate = ${lr},\n`,
        `    fp16 = not is_bfloat16_supported(),\n`,
        `    bf16 = is_bfloat16_supported(),\n`,
        `    logging_steps = 1,\n`,
        `    optim = "adamw_8bit",\n`,
        `    weight_decay = 0.01,\n`,
        `    lr_scheduler_type = "linear",\n`,
        `    seed = 3407,\n`,
        `    output_dir = "outputs",\n`,
        `    report_to = "none",\n`,
        `    save_strategy = "no",\n`,
        `)\n`,
        `\n`,
        `trainer = SFTTrainer(\n`,
        `    model = model,\n`,
        `    tokenizer = tokenizer,\n`,
        `    train_dataset = dataset,\n`,
        `    dataset_text_field = "text",\n`,
        `    max_seq_length = max_seq_length,\n`,
        `    packing = False,\n`,
        `    args = args,\n`,
        `)\n`,
        `\n`,
        `print("Training started — leave this tab open...")\n`,
        `trainer.train()\n`,
        `print("OK — training finished!")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# ========== STEP 7: Save your fine-tuned model ==========\n`,
        `model.save_pretrained("lora_model")\n`,
        `tokenizer.save_pretrained("lora_model")\n`,
        `!zip -r lora_model.zip lora_model\n`,
        `print("")\n`,
        `print("=" * 50)\n`,
        `print("YOUR MODEL IS READY")\n`,
        `print("=" * 50)\n`,
        `print("1. Look at the LEFT side of Colab (folder icon = Files)")\n`,
        `print("2. Find lora_model.zip")\n`,
        `print("3. Click the three dots → Download")\n`,
        `print("Save that zip file on your computer — that IS your fine-tuned model.")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "code",
      metadata: {},
      source: [
        `# ========== STEP 8: Test your model (optional but recommended) ==========\n`,
        `from unsloth import FastLanguageModel\n`,
        `\n`,
        `FastLanguageModel.for_inference(model)\n`,
        `\n`,
        `messages = [\n`,
        `    {"role": "user", "content": "Hello! Say one short sentence about yourself."},\n`,
        `]\n`,
        `inputs = tokenizer.apply_chat_template(\n`,
        `    messages, tokenize=True, add_generation_prompt=True, return_tensors="pt"\n`,
        `).to("cuda")\n`,
        `\n`,
        `outputs = model.generate(input_ids=inputs, max_new_tokens=64, use_cache=True)\n`,
        `print(tokenizer.decode(outputs[0], skip_special_tokens=True))\n`,
        `print("")\n`,
        `print("OK — if you see a reply above, your model works!")\n`,
      ],
      outputs: [],
      execution_count: null,
    },
    {
      cell_type: "markdown",
      metadata: {},
      source: [
        `# How to USE your model after training (beginners)\n`,
        `\n`,
        `You now have a file: **\`lora_model.zip\`** on your computer.\n`,
        `\n`,
        `That zip is your fine-tuned model (a small adapter on top of the base model).\n`,
        `\n`,
        `---\n`,
        `\n`,
        `## Option A — Easiest: keep using it in this Colab\n`,
        `\n`,
        `1. Stay in this notebook after training.\n`,
        `2. Change the test message in **STEP 8** and run that cell again.\n`,
        `3. You can chat with your model here for free while the session is alive.\n`,
        `\n`,
        `---\n`,
        `\n`,
        `## Option B — Upload to Hugging Face (share or reuse later)\n`,
        `\n`,
        `1. Create a free account: https://huggingface.co/join\n`,
        `2. Create an access token: https://huggingface.co/settings/tokens (read+write)\n`,
        `3. In a new Colab cell run:\n`,
        `\n`,
        `\`\`\`python\n`,
        `from huggingface_hub import login\n`,
        `login()  # paste your token when asked\n`,
        `\n`,
        `model.push_to_hub("YOUR_USERNAME/my-finetuned-model")\n`,
        `tokenizer.push_to_hub("YOUR_USERNAME/my-finetuned-model")\n`,
        `\`\`\`\n`,
        `\n`,
        `4. Your model page will be:\n`,
        `   \`https://huggingface.co/YOUR_USERNAME/my-finetuned-model\`\n`,
        `\n`,
        `Anyone (or you later) can load it with Unsloth using that repo name.\n`,
        `\n`,
        `---\n`,
        `\n`,
        `## Option C — Use on your PC with Ollama\n`,
        `\n`,
        `1. Install Ollama: https://ollama.com\n`,
        `2. See Unsloth docs for GGUF export: https://docs.unsloth.ai/basics/inference-and-deployment\n`,
        `3. Then: ollama create mymodel -f Modelfile && ollama run mymodel\n`,
        `\n`,
        `---\n`,
        `\n`,
        `## What to send to a friend / client\n`,
        `\n`,
        `- Send them **\`lora_model.zip\`** (or the Hugging Face link from Option B).\n`,
        `- Tell them the **base model name**: \`${modelName}\`\n`,
        `- They need that base model + your adapter to run it.\n`,
        `\n`,
        `You do **not** need to retrain to use it again — just load the saved adapter.\n`,
      ],
    },
  ];

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3",
      },
      language_info: { name: "python", version: "3.10.0" },
      accelerator: "GPU",
      colab: { provenance: [], gpuType: "T4" },
    },
    cells,
  };

  return JSON.stringify(notebook, null, 2);
}
